#!/bin/bash

COLS=8
ROWS=5
X=100
Y=100

cd "$( dirname "${BASH_SOURCE[0]}" )"
TMPFILE="$PWD/bitmoji.webp"

F="$(python3 bitmoji.py $COLS $ROWS $X $Y "$TMPFILE")"
if [ -n "$F" ]; then
    echo -n "file://$F" | xclip -selection clipboard -t text/uri-list
    xvkbd -window 'Telegram*' -xsendevent -text "\\Cv" 2>/dev/null
fi

